manifest = "e4bc3be09008b90aae56d99f1a73785966c5346b485a4e80e61f1713903c0b76"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "f9d6a7b63ef2902777b6078fdebc54e7a57aac03"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "4f59c5f06f11cd029a85d932ef51b9d511761f49"
